version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - apt-get update
      - apt-get install -y maven chromium-browser
      - export CHROMEDRIVER_PATH=/usr/lib/chromium-browser/chromedriver
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn test
