version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 18
    commands:
      - echo Entered the install phase...
      - apt-get update
      - apt-get install -y google-chrome-stable
      - LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
      - curl -sS -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - chmod +x chromedriver
      - mv chromedriver /usr/bin/chromedriver
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Entered the build phase...
      - cd tests
      - mvn test
